{
 "title": "迁移模板",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "迁移文件数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "migration_success_files_total", "legendFormat": "成功文件数" },
    { "expr": "migration_failed_files_total", "legendFormat": "失败文件数" }
   ]
  },
  {
   "title": "迁移进度（%）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(migration_success_files_total+migration_failed_files_total)*100/migration_total_files_total",
     "legendFormat": "迁移进度"
    }
   ]
  },
  {
   "title": "迁移节点入带宽（Mbps）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "netstat_input/1024*8", "legendFormat": "{{machine_ip}}" }
   ]
  },
  {
   "title": "迁移任务总入带宽（Mbps）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "sum(netstat_input)/1024*8", "legendFormat": "总入带宽" }
   ]
  },
  {
   "title": "迁移节点出带宽（Mbps）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "netstat_output*8/1024", "legendFormat": "{{machine_ip}}" }
   ]
  },
  {
   "title": "迁移任务总出带宽（Mbps）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "sum(netstat_output)/1024*8", "legendFormat": "总出带宽" }
   ]
  }
 ]
}